server:
  error:
    include-stacktrace: on_param
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: trace
